Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:2674: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
Traceback (most recent call last):
  File "/home/iarroyof/Projects/ov-llm-reasoning/seq2seq_T5.py", line 124, in calculate_validation_score
    bleu_score = bleu.corpus_score([[ref] for ref in target_text], generated_text).score
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/sacrebleu/metrics/base.py", line 414, in corpus_score
    self._check_corpus_score_args(hypotheses, references)
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/sacrebleu/metrics/base.py", line 258, in _check_corpus_score_args
    raise TypeError(f'{prefix}: {err_msg}')
TypeError: BLEU: Each element of `hyps` should be a string.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/iarroyof/Projects/ov-llm-reasoning/seq2seq_T5.py", line 208, in <module>
    main()
  File "/home/iarroyof/Projects/ov-llm-reasoning/seq2seq_T5.py", line 206, in main
    reasoning_pipeline.generate(val_loader, epoch)
  File "/home/iarroyof/Projects/ov-llm-reasoning/seq2seq_T5.py", line 84, in generate
    gen_score = self.calculate_validation_score(data, generated_ids)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iarroyof/Projects/ov-llm-reasoning/seq2seq_T5.py", line 132, in calculate_validation_score
    st()
    ^^
NameError: name 'st' is not defined